### ISSUE TITLE
Got a question

### ISSUE THREAD

**Issue by RODinteractive** [smartblade/BldMystery#4]
Sorry for "issue", but this is the only way to send you a message.
I was wondering if you have a discord server about BoD, I would like to follow and maybe even contribute if it's possible in any way. Here's my discord btw Rodhenik #6677

Best regards

**Comment by smartblade** [comment]
Sorry, I have not discord server.
You can use gitter chat https://gitter.im/BldMystery/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge to ask question

**Comment by smartblade** [comment]
@RODinteractive  Finally I have created discord server. Invite link: https://discord.gg/VNgGP8x
